"""ingridient

Revision ID: 51dd81529db8
Revises: 84e3c8401b46
Create Date: 2023-05-20 13:44:55.193145

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '51dd81529db8'
down_revision = '84e3c8401b46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_categories_parrent_category', table_name='categories')
    op.drop_table('categories')
    op.drop_table('drinks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drinks',
    sa.Column('ID', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active_constructor', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ID', name='drinks_pkey')
    )
    op.create_table('categories',
    sa.Column('ID', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('parrent_category', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parrent_category'], ['categories.ID'], name='categories_parrent_category_fkey'),
    sa.PrimaryKeyConstraint('ID', name='categories_pkey')
    )
    op.create_index('ix_categories_parrent_category', 'categories', ['parrent_category'], unique=False)
    # ### end Alembic commands ###
