"""ingridient

Revision ID: 541c3f095053
Revises: 51dd81529db8
Create Date: 2023-05-20 13:46:13.605004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541c3f095053'
down_revision = '51dd81529db8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
