"""empty message

Revision ID: 61b9b2c98ed9
Revises: cf2dbec8315b
Create Date: 2023-05-21 00:22:18.631502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '61b9b2c98ed9'
down_revision = 'cf2dbec8315b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('values_for_ingridients',
    sa.Column('ID', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('params_ingridients',
    sa.Column('ID', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('params_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('ingridient_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['ingridient_id'], ['ingridients.ID'], ),
    sa.ForeignKeyConstraint(['params_id'], ['values_for_ingridients.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('params_ingridients')
    op.drop_table('values_for_ingridients')
    # ### end Alembic commands ###
