"""empty message

Revision ID: 74d948a821da
Revises: 139dae067c40
Create Date: 2023-05-20 17:32:36.370947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74d948a821da'
down_revision = '139dae067c40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drink_ingridients', sa.Column('blurb', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drink_ingridients', 'blurb')
    # ### end Alembic commands ###
