"""init3

Revision ID: 84e3c8401b46
Revises: bd8acfea159d
Create Date: 2023-05-20 13:36:17.000286

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '84e3c8401b46'
down_revision = 'bd8acfea159d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('ID', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('parrent_category', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['parrent_category'], ['categories.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_categories_parrent_category'), 'categories', ['parrent_category'], unique=False)
    op.create_table('drinks',
    sa.Column('ID', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('is_active_constructor', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drinks')
    op.drop_index(op.f('ix_categories_parrent_category'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
