"""init2

Revision ID: bd8acfea159d
Revises: 84100ad4f4d5
Create Date: 2023-05-20 13:30:54.225711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd8acfea159d'
down_revision = '84100ad4f4d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
