"""empty message

Revision ID: cf2dbec8315b
Revises: 13b08d10b659
Create Date: 2023-05-20 22:03:35.009344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cf2dbec8315b'
down_revision = '13b08d10b659'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingridients',
    sa.Column('ID', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_foreign_key(None, 'drink_ingridients', 'ingridients', ['ingridient_id'], ['ID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drink_ingridients', type_='foreignkey')
    op.drop_table('ingridients')
    # ### end Alembic commands ###
